// Generated by export_index.py — do not edit by hand
export const ENTRIES = {
 "entry-0": {
  "text": "Quick links\nOrders\nShipping & Delivery\nReturns, Exchanges & Refunds\nPayments & Pricing\nProducts & Stock\nAccounts & Privacy\nPromotions & Loyalty\nContact & Support",
  "chunk_id": "chunk-0"
 },
 "entry-1": {
  "text": "How do I place an order? Add items to your cart, click Checkout, enter your delivery and payment details, and confirm. You'll receive an order confirmation email within a few minutes. If it doesn't arrive, check your spam folder before contacting us.",
  "chunk_id": "chunk-0"
 },
 "entry-2": {
  "text": "Do I need an account to order? No. Guest checkout is available. Creating an account lets you track orders, save addresses and payment methods, and view your order history.",
  "chunk_id": "chunk-0"
 },
 "entry-3": {
  "text": "How do I know my order went through? You'll get a confirmation email with your order number. If your payment was authorized but you received no email, your order may still have been created. You can contact support with the payment reference rather than reordering.",
  "chunk_id": "chunk-0"
 },
 "entry-4": {
  "text": "Can I change or cancel my order after placing it? You can change or cancel within 2 hours of placing the order, as long as it hasn't shipped. Log in to My Orders and select Modify or Cancel, or contact support with your order number. Once an order is packed for dispatch, we can't modify it — you'll need to return it after delivery.",
  "chunk_id": "chunk-0"
 },
 "entry-5": {
  "text": "How do I track my order? Once your order ships, we email you a tracking number and carrier link. You can also see live status under My Orders. Tracking can take up to [24 hours] to show movement after dispatch.",
  "chunk_id": "chunk-0"
 },
 "entry-6": {
  "text": "What do the order statuses mean?\nStatus\nWhat it means\nPending payment\nWe're waiting for your payment to be authorized\nProcessing\nPayment confirmed; we're picking and packing your items\nShipped\nYour parcel is with the carrier\nOut for delivery\nArriving today\nDelivered\nCarrier has confirmed delivery\nCancelled\nOrder was cancelled; any charge is being refunded",
  "chunk_id": "chunk-0"
 },
 "entry-7": {
  "text": "Can I order by phone or email? No , orders are placed through our website only.",
  "chunk_id": "chunk-0"
 },
 "entry-8": {
  "text": "I received the wrong item or something is missing. Contact us within [7 days] of delivery with your order number and a photo of what you received. We'll send the correct item or refund you, and cover return shipping.",
  "chunk_id": "chunk-1"
 },
 "entry-9": {
  "text": "Where do you ship? We ship to [USA, UK, India, Canada, UAE, Australia]. Some items can't be shipped to certain destinations due to size, battery content, or local regulations — restrictions are noted on the product page.",
  "chunk_id": "chunk-1"
 },
 "entry-10": {
  "text": "How much does shipping cost?\nMethod\nDelivery time\nCost\nStandard\n[3–5 business days]\n[$200 · Free over $500]\nExpress\n[1–2 business days]\n[$300]\nSame-day (select cities)\n[Order before 5 pm]\n[$400]\nInternational\n[7–14 business days]\n[Calculated at checkout]",
  "chunk_id": "chunk-1"
 },
 "entry-11": {
  "text": "Delivery times are estimates in business days and exclude weekends and public holidays.",
  "chunk_id": "chunk-1"
 },
 "entry-12": {
  "text": "When will my order ship? Orders placed before [9 PM] on a business day usually ship the same day. Orders placed after the cut-off, on weekends, or on holidays ship the next business day.",
  "chunk_id": "chunk-1"
 },
 "entry-13": {
  "text": "Do you offer free shipping? Yes — on orders over [$X500] to [USA, Canada, Japan, India UK Australia], using standard delivery. The threshold applies to the merchandise subtotal after discounts and before tax.",
  "chunk_id": "chunk-1"
 },
 "entry-14": {
  "text": "My tracking hasn't updated in several days. Carriers occasionally scan parcels inconsistently. If there's been no movement for [5 business days], contact us and we'll open an investigation with the carrier.",
  "chunk_id": "chunk-1"
 },
 "entry-15": {
  "text": "My parcel says delivered but I don't have it. Check with neighbours, building reception, and any safe-drop locations first, and look for a carrier card. If it still hasn't turned up after [24–48 hours], contact us within [2 days] of the delivery scan and we'll file a claim.",
  "chunk_id": "chunk-2"
 },
 "entry-16": {
  "text": "Can I change my delivery address after ordering? Only before dispatch. Contact support immediately with your order number. After dispatch, you may be able to redirect the parcel through the carrier's own tracking page.",
  "chunk_id": "chunk-2"
 },
 "entry-17": {
  "text": "Do I need to sign for my delivery? [Signature is required on orders over $600 / Signature is optional — you can leave delivery instructions at checkout.]",
  "chunk_id": "chunk-2"
 },
 "entry-18": {
  "text": "Are customs duties and import taxes included? [Yes — prices at checkout are landed-cost inclusive. / No — international orders may incur duties and taxes on arrival, payable by the recipient. These are set by your local customs authority and are outside our control.]",
  "chunk_id": "chunk-2"
 },
 "entry-19": {
  "text": "What is your return policy? You can return most items within [30 days] of delivery for a full refund, provided they're unused, in original condition, and in their original packaging with tags attached.",
  "chunk_id": "chunk-2"
 },
 "entry-20": {
  "text": "What can't be returned?\nPersonalized or custom-made items\nPerishable goods\nOpened hygiene, intimate, or beauty products\nDigital downloads and gift cards\nItems marked Final Sale",
  "chunk_id": "chunk-2"
 },
 "entry-21": {
  "text": "How do I start a return?\nGo to My Orders and select Return item, or email [support@shop_online.com] with your order number.\nChoose a reason and whether you want a refund or exchange.\nPrint the prepaid return label we email you (or arrange your own courier).\nPack the item securely and drop it at [carrier/drop-off point].",
  "chunk_id": "chunk-2"
 },
 "entry-22": {
  "text": "Who pays for return shipping? Returns for faulty, damaged, or incorrect items are free. For change-of-mind returns, [return shipping is free / a flat fee of $100 is deducted from your refund].",
  "chunk_id": "chunk-3"
 },
 "entry-23": {
  "text": "How long do refunds take? We inspect returns within [2 business days] of receipt. Once approved, refunds are issued to your original payment method and typically appear within [5–10 business days], depending on your bank or card issuer.",
  "chunk_id": "chunk-3"
 },
 "entry-24": {
  "text": "Can I exchange instead of refund? Yes — select Exchange when starting your return and choose the replacement size or colour, subject to availability. If the new item costs more, we'll send a payment link for the difference.",
  "chunk_id": "chunk-3"
 },
 "entry-25": {
  "text": "My item arrived damaged. Contact us within [48 hours] of delivery with photos of the item and the outer packaging. We'll arrange a replacement or refund at no cost to you.",
  "chunk_id": "chunk-3"
 },
 "entry-26": {
  "text": "Something broke after a few weeks — is it covered? Manufacturing defects are covered by a [12-month] warranty. Contact support with your order number and a description or photo of the fault. Damage from misuse, accidents, or normal wear isn't covered.",
  "chunk_id": "chunk-3"
 },
 "entry-27": {
  "text": "What payment methods do you accept?\nCredit and debit cards: [Visa, Mastercard, Amex]\nDigital wallets: [Apple Pay, Google Pay, PayPal]\n[Bank transfer / pay-by-bank]\n[Buy now, pay later: Afterpay, Klarna]\n[Store credit and gift cards]",
  "chunk_id": "chunk-3"
 },
 "entry-28": {
  "text": "Is it safe to pay on your site? Yes. Payments are processed by Checkout over an encrypted connection, and card details are tokenized — we never store your full card number on our servers. Card payments are also protected by 3-D Secure authentication.",
  "chunk_id": "chunk-4"
 },
 "entry-29": {
  "text": "My payment was declined. Why? Common reasons include an incorrect CVV or billing address, insufficient funds, an expired card, exceeding a daily limit, or your bank blocking an unfamiliar merchant. Check your details, then try again or use a different method. If it keeps failing, your bank can tell you the exact decline reason — we only see a generic code.",
  "chunk_id": "chunk-4"
 },
 "entry-30": {
  "text": "I was charged but have no order. This is usually a pending authorization, not a completed charge. It typically drops off your statement within [3–7 business days]. If it settles into an actual charge with no order confirmation, send us the amount, date, and last four digits of the card and we'll trace it.",
  "chunk_id": "chunk-4"
 },
 "entry-31": {
  "text": "Why do I see multiple charges? Each authorization attempt can appear separately on your statement. Failed attempts are released automatically. If duplicates remain after [7 business days], contact us.",
  "chunk_id": "chunk-4"
 },
 "entry-32": {
  "text": "When am I charged? [At the time you place the order / When your order ships.] Pre-orders are charged [at order time / when the item ships].",
  "chunk_id": "chunk-4"
 },
 "entry-33": {
  "text": "Are prices inclusive of tax? [Yes — displayed prices include VAT/sales tax. / No — tax is calculated at checkout based on your delivery address.]",
  "chunk_id": "chunk-4"
 },
 "entry-34": {
  "text": "What currency are prices in? Prices are shown in $. If you pay with a card issued in another currency, your bank may apply a conversion rate and foreign transaction fee.",
  "chunk_id": "chunk-4"
 },
 "entry-35": {
  "text": "Do you offer invoices or receipts for business purchases? Yes — a tax invoice is attached to your order confirmation email and available under My Orders. To add a company name or tax registration number, enter it at checkout.",
  "chunk_id": "chunk-5"
 },
 "entry-36": {
  "text": "How do I find the right size? Each product page has a size guide with measurements. When you're between sizes, we recommend M. Sizing can vary by brand, so check the guide on each product rather than assuming.",
  "chunk_id": "chunk-5"
 },
 "entry-37": {
  "text": "Are product photos accurate? We photograph products under neutral lighting, but screens vary, so colours may differ slightly from the real item.",
  "chunk_id": "chunk-5"
 },
 "entry-38": {
  "text": "An item is out of stock — will it come back? Click Notify me on the product page and we'll email you if it's restocked. Restock timing depends on the supplier, and some items are one-off runs that won't return.",
  "chunk_id": "chunk-5"
 },
 "entry-39": {
  "text": "Can I reserve or pre-order an item? [Pre-orders are available on items marked Pre-order, with the expected ship date shown on the product page. / We don't currently offer reservations.]",
  "chunk_id": "chunk-5"
 },
 "entry-40": {
  "text": "Do you offer bulk or wholesale pricing? Yes — for orders over [100 units], contact [wholesale@shop_online..com] for a quote.",
  "chunk_id": "chunk-5"
 },
 "entry-41": {
  "text": "How do I create an account? Click Sign up, enter your email, and set a password. You can also sign in with [Google / Apple].",
  "chunk_id": "chunk-5"
 },
 "entry-42": {
  "text": "I forgot my password. Click Forgot password on the login page and we'll email a reset link, valid for [60 minutes]. If it doesn't arrive, check spam or confirm you're using the email you registered with.",
  "chunk_id": "chunk-5"
 },
 "entry-43": {
  "text": "How do I update my email, address, or payment methods? Go to My Account → Settings. Changes to saved addresses don't affect orders already placed.",
  "chunk_id": "chunk-5"
 },
 "entry-44": {
  "text": "How do I delete my account? Email [privacy@shop_online.com] from your registered address, or use My Account → Delete account. We'll delete your personal data within [30 days], except records we're legally required to retain, such as transaction records for tax purposes.",
  "chunk_id": "chunk-6"
 },
 "entry-45": {
  "text": "What do you do with my data? We use it to process orders, provide support, and — with your consent — send marketing. We don't sell your personal data. See our Privacy Policy for full detail.",
  "chunk_id": "chunk-6"
 },
 "entry-46": {
  "text": "How do I unsubscribe from marketing emails? Click Unsubscribe at the bottom of any marketing email, or turn off email preferences under My Account. You'll still receive transactional emails about orders you place.",
  "chunk_id": "chunk-6"
 },
 "entry-47": {
  "text": "How do I use a discount code? Enter it in the Promo code field at checkout and click Apply. Only one code can be used per order unless stated otherwise.",
  "chunk_id": "chunk-6"
 },
 "entry-48": {
  "text": "My discount code isn't working. Check that it hasn't expired, that your order meets the minimum spend, and that the items are eligible — sale items and [category] are often excluded. Codes are case-sensitive.",
  "chunk_id": "chunk-6"
 },
 "entry-49": {
  "text": "Can I apply a code after ordering? Unfortunately not. Codes must be applied at checkout.",
  "chunk_id": "chunk-6"
 },
 "entry-50": {
  "text": "Do you have a loyalty program? Yes — earn [1 point per $1] spent, redeemable at [100 points = $5]. Points post after your return window closes and expire after [12 months] of inactivity.",
  "chunk_id": "chunk-6"
 },
 "entry-51": {
  "text": "Do you sell gift cards? Yes, in denominations of [$25–$500], delivered by email. Gift cards don't expire and aren't refundable for cash.",
  "chunk_id": "chunk-7"
 },
 "entry-52": {
  "text": "How do I reach you?\nChannel\nDetails\nResponse time\nEmail\n[support@shop_online.com]\n[Within 24 hours]\nLive chat\nBottom-right of any page\n[Instant during business hours]\nPhone\n[+1 555 000 0000]\n[Mon–Fri, 9am–6pm]\nSocial\n[@shop_online]\n[Within 48 hours]",
  "chunk_id": "chunk-7"
 },
 "entry-53": {
  "text": "What information should I include when contacting support? Your order number, the email used to order, and a clear description of the issue. For damaged or incorrect items, attach photos. This lets us resolve most cases in one reply.",
  "chunk_id": "chunk-7"
 },
 "entry-54": {
  "text": "Do you have physical stores? [ No, we're online only.]",
  "chunk_id": "chunk-7"
 },
 "entry-55": {
  "text": "How do I report a problem with the website? Email [support@shop_online.com] with the page URL, your device and browser, and a screenshot if possible.",
  "chunk_id": "chunk-7"
 }
};
export const SYSTEM_PROMPT = "You are the Shop Online customer support assistant.\nAnswer the customer's question using ONLY the FAQ excerpts provided.\n- Be concise and friendly: 1-4 sentences, or a short list when listing steps or options.\n- Reply in plain text only: no markdown, no **bold**, no headings. Use \"- \" for list items.\n- Values in [square brackets] are the store's actual policy values; state them without the brackets.\n- EXCEPTION: brackets containing alternatives separated by \" / \" (e.g. \"[free / a $100 fee]\") mean\n  that policy is NOT confirmed. Never pick one option. Say that detail isn't confirmed and suggest\n  contacting support@shop_online.com for it.\n- If the excerpts don't answer the question, say you don't have that information and suggest\n  contacting support@shop_online.com. Never invent policies, prices, or timeframes.";
